# Generated by Django 4.2 on 2026-02-20 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_patient_created_at_alter_patient_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_type', models.CharField(blank=True, choices=[('balanced', 'Balanced Diet'), ('keto', 'Keto Diet'), ('vegan', 'Vegan Diet'), ('low_carb', 'Low Carb')], max_length=20, null=True)),
                ('calories_per_day', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft (AI Generated)'), ('approved', 'Approved by Doctor'), ('published', 'Published by Admin')], default='draft', max_length=20, null=True)),
                ('ai_generated_plan', models.TextField(blank=True, help_text='AI generated diet plan content', null=True)),
                ('doctor_notes', models.TextField(blank=True, help_text='Notes from doctor approval', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_diet_plans', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DietRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.CharField(blank=True, max_length=100, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('carbs', models.FloatField(blank=True, null=True)),
                ('fat', models.FloatField(blank=True, null=True)),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.dietplan')),
            ],
        ),
    ]
