# Generated by Django 4.2 on 2026-03-31 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0006_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fat', models.FloatField()),
                ('category', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=50)),
                ('is_veg', models.BooleanField(default=True)),
                ('is_diabetic_friendly', models.BooleanField(default=True)),
                ('is_heart_friendly', models.BooleanField(default=True)),
                ('is_bp_friendly', models.BooleanField(default=True)),
                ('contains_milk', models.BooleanField(default=False)),
                ('contains_nuts', models.BooleanField(default=False)),
                ('contains_gluten', models.BooleanField(default=False)),
                ('cuisine', models.CharField(choices=[('south', 'South Indian'), ('north', 'North Indian'), ('mixed', 'Mixed')], default='mixed', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PatientHealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('height', models.FloatField(help_text='Height in cm')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('goal', models.CharField(choices=[('loss', 'Weight Loss'), ('gain', 'Weight Gain'), ('maintain', 'Maintain Weight')], default='maintain', max_length=10)),
                ('diabetes', models.BooleanField(default=False)),
                ('hypertension', models.BooleanField(default=False, verbose_name='Blood Pressure')),
                ('thyroid', models.BooleanField(default=False)),
                ('heart_disease', models.BooleanField(default=False)),
                ('pcos', models.BooleanField(default=False, verbose_name='PCOS (Females)')),
                ('other_symptoms', models.TextField(blank=True, help_text='e.g., Acidity, Joint pain', null=True)),
                ('milk_allergy', models.BooleanField(default=False)),
                ('nuts_allergy', models.BooleanField(default=False)),
                ('gluten_allergy', models.BooleanField(default=False)),
                ('seafood_allergy', models.BooleanField(default=False)),
                ('custom_allergies', models.CharField(blank=True, max_length=200, null=True)),
                ('dietary_preference', models.CharField(choices=[('veg', 'Vegetarian'), ('non-veg', 'Non-vegetarian'), ('vegan', 'Vegan'), ('egg', 'Eggetarian')], default='veg', max_length=10)),
                ('meal_frequency', models.IntegerField(default=3, help_text='Number of meals per day')),
                ('cuisine_preference', models.CharField(choices=[('south', 'South Indian'), ('north', 'North Indian'), ('mixed', 'Mixed')], default='mixed', max_length=10)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (Office job)'), ('light', 'Light Activity'), ('moderate', 'Moderate Activity'), ('heavy', 'Heavy Activity (Athlete)')], default='sedentary', max_length=15)),
                ('sleep_hours', models.FloatField(default=8)),
                ('water_intake', models.FloatField(default=2, help_text='Liters per day')),
                ('smoking_alcohol', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to='home.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'AI Generated'), ('reviewed', 'Reviewed by Admin'), ('approved', 'Approved')], default='draft', max_length=10)),
                ('daily_calories', models.IntegerField(blank=True, null=True)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('health_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.patienthealthprofile')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plan', to='home.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DailyMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('meal_type', models.CharField(max_length=20)),
                ('food_name', models.CharField(max_length=200)),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fat', models.FloatField()),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='diet.dietplan')),
            ],
        ),
    ]
