# Generated by Django 4.2 on 2026-02-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietrecommendation',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='dietrecommendation',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='dietrecommendation',
            name='food_item',
        ),
        migrations.RemoveField(
            model_name='dietrecommendation',
            name='protein',
        ),
        migrations.AddField(
            model_name='dietrecommendation',
            name='meal_time',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dietrecommendation',
            name='recommendation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
