# Generated by Django 4.2 on 2026-03-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_doctor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='token_number',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('appointment_date', 'token_number')},
        ),
    ]
