# Generated by Django 4.2 on 2026-03-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='token_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
    ]
